### ISSUE TITLE
Unhandled exception crash when clicking our largest solution

### ISSUE THREAD

**Issue by richardhardinguk** [MscrmTools/MscrmTools.SolutionLayersExplorer#1]
When browsing solutions, if we click into our largest one, we get an unhandled exception crash:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MscrmTools.SolutionLayersExplorer.UserControls.ComponentsPicker.DisplayComponents(List`1 componentsDefs)
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

After this it lists out all the assembly versions.

We are still able to click into the solution and browse it, and review and remove unmanaged layers, so it's not a terminal bug.

The solution being browsed contains:
Attribute - 618
Entity - 164
Enttiy Relationship - 62
Field security profile - 11
Option Set - 145

Although as a null reference exception, I guess it's probably not to do with the size.

Happy to provide any more debugging info if you can provide instructions.

**Comment by MscrmTools** [comment]
Hi @richardhardinguk, thank you for reporting this issue.

Can you test this version and tell me if it still produces an error :
[MscrmTools.SolutionLayersExplorer.zip](https://github.com/MscrmTools/MscrmTools.SolutionLayersExplorer/files/8360503/MscrmTools.SolutionLayersExplorer.zip)

**Comment by richardhardinguk** [comment]
Hi, same error.

**Comment by richardhardinguk** [comment]
No longer experiencing this issue. Closing off.
