### ISSUE TITLE
Tool is not working for on-premise instance

### ISSUE THREAD

**Issue by jaylak12345** [MscrmTools/MscrmTools.SolutionLayersExplorer#3]
Tool is not working for on-premise instance. This is the error : 
Error when loading solutions: The entity with a name = 'solutioncomponentdefinition' with namemapping = 'Logical' was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=2686213924, MinActiveRowVersion=2686213924_

**Comment by MscrmTools** [comment]
@jaylak12345 This simply means that this tool requires feature only available online. So it cannot work onpremise
