### ISSUE TITLE
[BUG] Active layer on SdkMessageProcessingStep not seen

### ISSUE THREAD

**Issue by sybaris** [MscrmTools/MscrmTools.SolutionLayersExplorer#5]
Hi,

I use your wonderful tool very often, and thank for it.
I can not see Active Layers on SdkMessageProcessingStep with your tool, but I saw them on make.powerapps.com.

Note that the following code return to me the the active layers :
```
select *
from msdyn_componentlayer
where msdyn_solutioncomponentname= 'SdkMessageProcessingStep'
and msdyn_componentid='af003e42-e94d-e811-a957-000d3a28a7dd'

```
But if I replace **Sdk**MessageProcessingStep by **SDK**MessageProcessingStep, the same query does not return anything. And in Enum.cs, I saw that it's the second case that is used.
Not sure, but perharps that could explain the bug ?

Regards
Sybaris

**Comment by MscrmTools** [comment]
Hi @sybaris 
Thank you for reporting it! I will investigate this issue

**Comment by MscrmTools** [comment]
You are correct! Changing the casing does make the active layer found!
I will publish a fix but I need to wait to get my new code signing certificate and it seems to take a while...

**Comment by MscrmTools** [comment]
The new version has been released
