### ISSUE TITLE
Number of conditions in query exceed maximum limit.

### ISSUE THREAD

**Issue by jxs0900** [MscrmTools/MscrmTools.SolutionLayersExplorer#7]
Takes way too long to load anything.  Can NEVER load the default solution.  Aggravating to use.

---
- Deployment: OnPremise
- DB Version: 9.1.11.26
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.10.67
- Tool Version: 1.2023.10.20

**Comment by MscrmTools** [comment]
Would you be able to test with this version?

[MscrmTools.SolutionLayersExplorer.zip](https://github.com/MscrmTools/MscrmTools.SolutionLayersExplorer/files/13562787/MscrmTools.SolutionLayersExplorer.zip)

**Comment by jxs0900** [comment]
It's working with that version.  Thank you.  I'm sorry for being an asshole.  I'm so frustrated trying to figure out layering and why I am having so much trouble getting my changes to show up.

**Comment by MscrmTools** [comment]
I know that feeling! That's why I ended up by creating this tool.

Than you for having helped to resolve an issue here. I will push publicly this new version.

**Comment by sudershankh** [comment]
@MscrmTools We are Observing same issue as we have 800-900 sdksteps  in the solution , 

Went through the code here is the Resolution : We can chunk the pluginStepComponents to 500 each and then Add it to components

I have tried in Local and it works Let me know on your thoughts and Can i raise PR ?

**Comment by MscrmTools** [comment]
Please create a PR, yes

Thank you

**Comment by MscrmTools** [comment]
Fixed in latest version. Thanks @sudershankh
