### ISSUE TITLE
Exception : RemoveActiveCustomizations is not supported for components of type SdkMessageProcessingStepImage

### ISSUE THREAD

**Issue by sybaris** [MscrmTools/MscrmTools.SolutionLayersExplorer#8]
Hi,

Trying to remove 2 active layers 
![image](https://github.com/MscrmTools/MscrmTools.SolutionLayersExplorer/assets/11009997/9ac5f124-a777-4bb4-af7e-ccbdd975f19f)

I had this exception :
![image](https://github.com/MscrmTools/MscrmTools.SolutionLayersExplorer/assets/11009997/1fadc430-caea-44b9-963e-8a99019e4853)

Regards
Sybaris

**Comment by MscrmTools** [comment]
I know. Even if I added support to detect unmanaged layer or plugin step images, it's not yet possible to remove them.
It's a defect on Microsoft side and I cannot do anything.
I reported this weeks ago and I'm still waiting they fix this.

**Comment by sybaris** [comment]
Hi
Thanks for your answer.
I have also created a ticket on our side to Microsoft support. They have tell us that they have already this in their backlog, but no ETA.
Regards
Sybaris
