### ISSUE TITLE
[Feature Request] : Get the date/time of the active layer.

### ISSUE THREAD

**Issue by sybaris** [MscrmTools/MscrmTools.SolutionLayersExplorer#9]
Hi,

Something that could be interesting is to know when the active layer hase been created.
This is a valuable information to display.

Thanks for advance
Sybaris

**Comment by MscrmTools** [comment]
Unfortunately, I did not find where to read that information. There is an overwritetime attribute but it's always a default date.
If you know where to find this information, please reopen this issue

**Comment by sybaris** [comment]
I just understood the interest of the overwritetime field. Certainly it is the default date for the highest layer, but for the previous layers, it corresponds to the override date of the layer.
So Solution Layer Explorer displays already this information in the overwritetime of the previous layer...
Thanks for your help
